name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload built package to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/heitzfit4.js
          asset_name: heitzfit4.js
          tag: ${{ github.ref }}
          overwrite: true
